--u Se agregaron endPoints de actualizar y desactivar docente.
UNICAH-ICC-SAP/GestionPracticasApi pull request #6
Opened 2024-10-31 04:40 UTC by jarquinlesman

##.##: [FEATURE] Actualización de docentes.

* UNICAH-ICC-SAP/GestionPracticasWeb/issues/5 Se modificaron los siguientes endPoints: 1) insert para que el estadoDocente sea igual a 1 (activo). 2) findAll para que solamente muestre los docentes que están activos.
* UNICAH-ICC-SAP/GestionPracticasWeb/issues/5 Se agregaron los siguientes endPoints: 1) update para poder actualizar la información de un docente existente. 2) updateStatus para cambiar el estadoDocente a 0 (inactivo).

2024-10-31 04:59 UTC, Acalix-unicah requested changes
Realice las correcciones solicitadas.

2024-10-31 04:59 UTC, Acalix-unicah commented on app/controllers/docenteController.js
>      Docente.findAll({ where: req.query })
Este método de filtrado no traerá la facultad, lo que hace que el front requiera una consulta para obtener facultades.

2024-10-31 05:04 UTC, jarquinlesman commented on app/controllers/docenteController.js
>      Docente.findAll({ where: req.query })
El método que debo corregir es findBy o findAll?

2024-11-05 06:05 UTC, Acalix-unicah commented on app/controllers/docenteController.js
>      Docente.findAll({ where: req.query })
El método findBy

2024-11-05 06:08 UTC, jarquinlesman commented on app/controllers/docenteController.js
>      Docente.findAll({ where: req.query })
Ya hice el git push, ya que le mostré en clase y me dijo que estaba bien, solo debía hacer el git push.

2024-11-06 21:59 UTC, Acalix-unicah approved these changes
Solicitud de cambios resueltos

2024-11-06 21:59 UTC, merged